export enum ApiStatus {
  NOT_FOUND = "NOT_FOUND",
  SERVER_ERROR = "SERVER_ERROR",
  UNAUTHORIZED = "UNAUTHORIZED",
  UNAUTHENTICATED = "UNAUTHENTICATED",
  CONFLICT = "CONFLICT",
  UNKNOWN = "UNKNOWN",
  BAD_REQUEST = "BAD_REQUEST",
}
