"""fix_fk

Revision ID: 14ec583828eb
Revises: 5c3ba4dc59ee
Create Date: 2025-04-28 17:15:13.019856

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14ec583828eb"
down_revision: Union[str, None] = "5c3ba4dc59ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "chat_messages_conversation_id_fkey", "chat_messages", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "chat_messages", "conversations", ["conversation_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chat_messages", type_="foreignkey")
    op.create_foreign_key(
        "chat_messages_conversation_id_fkey",
        "chat_messages",
        "users",
        ["conversation_id"],
        ["id"],
    )
    # ### end Alembic commands ###
