"""add created_at

Revision ID: 53ed27fde306
Revises: 14ec583828eb
Create Date: 2025-04-30 14:50:28.876946

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53ed27fde306"
down_revision: Union[str, None] = "14ec583828eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_messages", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "conversations", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "created_at")
    op.drop_column("chat_messages", "created_at")
    # ### end Alembic commands ###
